// Generated by CoffeeScript 1.3.3

// ==UserScript==
// @match https://trello.com/board/*
// ==/UserScript==
;

var body;

(function(fn) {
  var s;
  s = document.createElement('script');
  s.textContent = '(' + fn + ')()';
  return document.body.appendChild(s);
})(body = function() {
  var cookie_name, debounce, is_active, recalc_list_size, recalc_list_size_debounced, save_cookie, toggle, _ref;
  debounce = function(fn, time) {
    return _.debounce(time, fn);
  };
  (function(style) {
    return $('<style>').attr({
      type: 'text/css'
    }).text(style).appendTo('head');
  })(".toggler { cursor: pointer; }\n.toggler.active { background-color: gainsboro; }");
  recalc_list_size = function() {
    return Controller.boardCurrent.view.renderLists();
  };
  recalc_list_size_debounced = debounce(2000, recalc_list_size);
  toggle = function(list, button, from_cookie) {
    if (from_cookie == null) {
      from_cookie = false;
    }
    button.toggleClass('active');
    list.toggle().toggleClass('list invisible-list');
    if (!from_cookie) {
      save_cookie();
      return recalc_list_size_debounced();
    }
  };
  $(document).on('DOMNodeInserted', '.list', debounce(200, function() {
    if (!$('.toggler').length) {
      $('#board-header').find('.toggler').remove().end().append($('.list, .invisible-list').map(function(_, list) {
        var button, name;
        list = $(list);
        button = $('<a>').text(name = list.find('h2')[0].firstChild.textContent).addClass('quiet org-name toggler active');
        button.click(function() {
          return toggle(list, button);
        });
        if (!is_active(name)) {
          toggle(list, button, true);
        }
        return button.get(0);
      }));
      if ($('.invisible-list').length) {
        return recalc_list_size();
      }
    }
  }));
  cookie_name = 'inactive_lists_' + ((_ref = location.href.match(/\/board\/[^\/]+\/([^\/]+)/)) != null ? _ref[1] : void 0) || 'unknown';
  save_cookie = function() {
    return document.cookie = cookie_name + '=|' + $('.toggler:not(.active)').map(function() {
      return this.textContent;
    }).get().join('|') + '|';
  };
  return is_active = function(name) {
    return !(document.cookie.match(RegExp("" + cookie_name + "=[^;]*\\|" + name + "\\|")));
  };
});
